stages:
  - build
  - deploy
#test
variables:
  ANSIBLE_FORCE_COLOR: 'true'

build-stage:
  stage: build
  tags:
    - k8s-runner
  script: docker build -t krdsite24/djangob . && docker push krdsite24/djangob

deploy-stage:

  stage: deploy
  tags:
    - k8s-runner
  script:
    - /home/gitlab-runner/.local/bin/ansible-playbook -i ansible/hosts.yml  -v ansible/deploy.yml
    
  