apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
        tier: backend
    spec:
      nodeSelector:
          dbserver: "true"
      containers:
        - name: django-container
          image: krdsite24/djangob:latest
          command: ["/bin/sh"]
          args: ["-c", " ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"]


