---
- hosts: all


  tasks:
  - name: deleting deployment
    shell:
     cmd: kubectl delete deployment django
    ignore_errors: false

  - name: apply deployment 
    shell:
     chdir: /opt/k8s/docker
     cmd: kubectl apply -f k8s/deployment.yaml
    ignore_errors: false
  
  