---
- hosts: all
  tasks:
  - name: Create a k8s namespace
    community.kubernetes.k8s:
      name: django-app
      api_version: v1
      kind: Namespace
      state: present
  - name: Create a Service object from an inline definition
    community.kubernetes.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: django-service
          namespace: django-app
        spec:
          selector:
            app: django
          ports:
           - protocol: TCP
             targetPort: 8000
             port: 8000
             nodePort: 30080
          type: NodePort
  - name: Remove an existing deployment object
    community.kubernetes.k8s:
      state: absent
      api_version: v1
      kind: Deployment
      namespace: django-app
      name: django        
  - name: create deployent
    community.kubernetes.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Deployment
        metadata:
          name: django
          namespace: django-app
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: django
          template:
            metadata:
              labels:
                app: django
                tier: backend
            spec:
              containers:
                - name: django-container
                  image: krdsite24/djangob:latest
                  command: ["/bin/sh"]
                  args: ["-c", " ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"]
