kind: Service
apiVersion: v1
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres-container
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30000
      targetPort: 5432
  # type: NodePort
